name: Docker Image CI - X86_64/AARCH64 for Chimera Linux to continuous tags

on:
  push:
    branches: [ "main" ]
    tags:
      - 'continuous'
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:    
  schedule:
    - cron: "41 18 * * *"  
    - cron: "26 6 * * *" 

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --tag builderust .

    - name: build static program with chimera linux docker 
      run: |
        docker run --cidfile=builderust.cid builderust true
        docker cp "$(cat builderust.cid):work/artifact/." .

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./bcachefs.tar.xz
        asset_name: bcachefs-${{ runner.os }}-${{ runner.arch }}.tar.xz
        tag: refs/tags/continuous
        overwrite: true
        body: "Fully static bcachefs tools binary using chimera linux docker containers."          
